### ISSUE TITLE
Duplicate coordinates

### ISSUE THREAD

**Issue by RudiZhang** [MatisseBE/vatglasses-converter#1]
![image](https://github.com/MatisseBE/vatglasses-converter/assets/40914896/c887e94e-2048-49d3-95ab-855865b51608)
![image](https://github.com/MatisseBE/vatglasses-converter/assets/40914896/6f265e08-76ae-4dda-b14a-6ddcb3845458)

Hi! As you can see in the screenshot. Some of the points are duplicated when using the tool. Would you maybe have a look? Thanks a lot!

same for some fir
https://github.com/lennycolton/vatglasses-data/blob/main/data/lf.json
https://github.com/lennycolton/vatglasses-data/blob/main/data/eh.json
https://github.com/lennycolton/vatglasses-data/blob/main/data/fs.json

**Comment by MatisseBE** [comment]
This is because the sectors are made up of sector lines. Euroscope does not care about the order, however VATGLASSES does. So we connect these sector lines by connecting the ends based on matching coordinates. All the duplicate coordinates you see are "stitches" of those sector lines. 

I could try to add a function to remove either end of the stitch. (Which I thought what "dominoes.remove(dominoes[j])" was for)

**Comment by RudiZhang** [comment]
> This is because the sectors are made up of sector lines. Euroscope does not care about the order, however VATGLASSES does. So we connect these sector lines by connecting the ends based on matching coordinates. All the duplicate coordinates you see are "stitches" of those sector lines.
> 
> I could try to add a function to remove either end of the stitch. (Which I thought what "dominoes.remove(dominoes[j])" was for)

Ah! I see! Thanks anyway :):)

**Comment by MatisseBE** [comment]
@RudiZhang I added a dumb function to remove the duplicates. Any chance you could test it? I suggest you take a look at the changes I made such that you do not need to remake the whole script. (Create AIRSPACE from ESE.py)

**Comment by RudiZhang** [comment]
> @RudiZhang I added a dumb function to remove the duplicates. Any chance you could test it? I suggest you take a look at the changes I made such that you do not need to remake the whole script. (Create AIRSPACE from ESE.py)

Thanks! I just tested it and looks good.

**Comment by MatisseBE** [comment]
Fixed
